project:
  type: website

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package
  package: openprotein
  # write sidebar data to this file
  sidebar: _sidebar.yml
  sections:
    - title: Overview
      desc: Welcome to the OpenProtein python client documentation! <br><br> Our workflows follow an asynchronous POST and GET framework. Once you initiate a task the system will schedule the job for retrieval later, once the work is complete. This means that even for tasks that may take a while to complete, your request will return immediately. <br><br> The job objects contain a job ID (job_id) which can be used to resume a workflow from where you left off! See the notebooks for demonstrations. 
      contents:
        - base.APISession
    - title: Assay Data 
      desc: Upload your dataset to OpenProtein's engineering platform for train, predict and design tasks.
      contents:
        - api.data.DataAPI
        - api.data.AssayDataset
    - title: Train
      desc: Train model(s) on your measured properties to enable predictions for new sequences! These workflows can additionally perform cross-validation on your models to estimate uncertainty. /n A trained model is required before you can utilize predict or design endpoints.
      contents:
        - api.train.TrainingAPI
        - api.train.TrainFuture
    - title: Design
      desc: Design new sequences based on your stated objectives and our genetic algorithm!
      contents:
        - api.design.DesignAPI
        - api.design.DesignFuture
    - title: Predict
      desc: Predict properties on arbitary sequences with your OpenProtein trained models! You can make predictions for single sequences as well as single mutant variants of the sequence.<br><br> Note, that you must first train a model with the train endpoints (see above).
      contents:
        - api.predict.PredictAPI
        - api.predict.PredictFuture
    - title: Protein Evolutionary Transformer (PoET)
      desc: Use our generative Protein Evolutionary Transformer (PoET) model for de novo generation of proteins, evaluation of protein fitness, and single site mutant analysis of proteins. These workflows are all possible without prior wetlab data, and therefore do not require assaydata to be pre-loaded!
      contents:
        - api.poet.PoetAPI
        - api.poet.PoetScoreFuture
        - api.poet.PoetSingleSiteFuture
        - api.poet.PoetGenerateFuture
        - api.poet.PromptFuture
        - api.poet.MSAFuture
    - title: Embeddings
      desc: Create embeddings for your protein sequences using open-source and proprietary models!
      contents:
        - api.embedding.EmbeddingAPI
        - api.embedding.EmbeddingResultFuture
        - api.embedding.ProtembedModel
        - api.embedding.SVDModel