package:
  name: openprotein_python
  version: 0.1.1b8

source:
  path: ./

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3.7
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.0
    - pydantic >=1.0
    - tqdm >=4.0
    - pandas >=1.0

about:
  home: https://www.openprotein.ai/
  license: MIT
  summary: OpenProtein Python interface.
  description: A Python interface for OpenProtein.
  doc_url: https://docs.openprotein.ai/
  dev_url: https://github.com/OpenProteinAI/openprotein-python
