# api.poet.PoetGenerateFuture { #openprotein.api.poet.PoetGenerateFuture }

`api.poet.PoetGenerateFuture()`

Represents a result of a PoET generation job.

## Attributes

| Name    | Type       | Description                                     |
|---------|------------|-------------------------------------------------|
| session | APISession | An instance of APISession for API interactions. |
| job     | Job        | The PoET scoring job.                           |

Methods:
    stream() -> Iterator[PoetScoreResult]:
        Stream the results of the PoET generation job.

## Methods

| Name | Description |
| --- | --- |
| [stream](#openprotein.api.poet.PoetGenerateFuture.stream) | Stream the results from the response. |

### stream { #openprotein.api.poet.PoetGenerateFuture.stream }

`api.poet.PoetGenerateFuture.stream(self)`

Stream the results from the response.

#### Returns

| Type   | Description                                               |
|--------|-----------------------------------------------------------|
| Yield  | A result object containing the sequence, score, and name. |

#### Raises

| Type     | Description           |
|----------|-----------------------|
| APIError | If the request fails. |