# api.design.DesignAPI { #openprotein.api.design.DesignAPI }

`api.design.DesignAPI(self, session)`

API interface for calling Design endpoints

## Methods

| Name | Description |
| --- | --- |
| [create_design_job](#openprotein.api.design.DesignAPI.create_design_job) | Start a protein design job based on your assaydata, a trained ML model and Criteria (specified here). |
| [get_design_results](#openprotein.api.design.DesignAPI.get_design_results) | Retrieves the results of a Design job. |
| [load_job](#openprotein.api.design.DesignAPI.load_job) | Reload a Submitted job to resume from where you left off! |

### create_design_job { #openprotein.api.design.DesignAPI.create_design_job }

`api.design.DesignAPI.create_design_job(self, design_job)`

Start a protein design job based on your assaydata, a trained ML model and Criteria (specified here).

#### Parameters

| Name         | Type            | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | Default    |
|--------------|-----------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `design_job` | DesignJobCreate | The details of the design job to be created, with the following parameters: - assay_id: The ID for the assay. - criteria: A list of CriterionItem lists for evaluating the design. - num_steps: The number of steps in the genetic algo. Default is 8. - pop_size: The population size for the genetic algo. Default is None. - n_offsprings: The number of offspring for the genetic algo. Default is None. - crossover_prob: The crossover probability for the genetic algo. Default is None. - crossover_prob_pointwise: The pointwise crossover probability for the genetic algo. Default is None. - mutation_average_mutations_per_seq: The average number of mutations per sequence. Default is None. - mutation_positions: A list of positions where mutations may occur. Default is None. | _required_ |

#### Returns

| Type         | Description                                 |
|--------------|---------------------------------------------|
| DesignFuture | The created job as a DesignFuture instance. |

### get_design_results { #openprotein.api.design.DesignAPI.get_design_results }

`api.design.DesignAPI.get_design_results(self, job_id, page_size=None, page_offset=None)`

Retrieves the results of a Design job.

#### Parameters

| Name          | Type                   | Description                                                                       | Default    |
|---------------|------------------------|-----------------------------------------------------------------------------------|------------|
| `job_id`      | str                    | The ID for the design job                                                         | _required_ |
| `page_size`   | typing.Optional\[int\] | The number of results to be returned per page. If None, all results are returned. | `is None`  |
| `page_offset` | typing.Optional\[int\] | The number of results to skip. If None, defaults to 0.                            | `is None`  |

#### Returns

| Type      | Description                                 |
|-----------|---------------------------------------------|
| DesignJob | The job object representing the Design job. |

#### Raises

| Type      | Description                          |
|-----------|--------------------------------------|
| HTTPError | If the GET request does not succeed. |

### load_job { #openprotein.api.design.DesignAPI.load_job }

`api.design.DesignAPI.load_job(self, job_id)`

Reload a Submitted job to resume from where you left off!

#### Parameters

| Name     | Type   | Description                                               | Default    |
|----------|--------|-----------------------------------------------------------|------------|
| `job_id` | str    | The identifier of the job whose details are to be loaded. | _required_ |

#### Returns

| Type   | Description   |
|--------|---------------|
| Job    | Job           |

#### Raises

| Type       | Description                         |
|------------|-------------------------------------|
| HTTPError  | If the request to the server fails. |
| InvalidJob | If the Job is of the wrong type     |