# api.predict.PredictAPI { #openprotein.api.predict.PredictAPI }

`api.predict.PredictAPI(self, session)`

API interface for calling Predict endpoints

## Methods

| Name | Description |
| --- | --- |
| [create_predict_job](#openprotein.api.predict.PredictAPI.create_predict_job) | Creates a new Predict job for a given list of sequences and a trained model. |
| [create_predict_single_site](#openprotein.api.predict.PredictAPI.create_predict_single_site) | Creates a new Predict job for single site mutation analysis with a trained model. |
| [get_prediction_results](#openprotein.api.predict.PredictAPI.get_prediction_results) | Retrieves the results of a Predict job. |
| [get_single_site_prediction_results](#openprotein.api.predict.PredictAPI.get_single_site_prediction_results) | Retrieves the results of a single site Predict job. |
| [load_job](#openprotein.api.predict.PredictAPI.load_job) | Reload a Submitted job to resume from where you left off! |

### create_predict_job { #openprotein.api.predict.PredictAPI.create_predict_job }

`api.predict.PredictAPI.create_predict_job(self, sequences, train_job, model_ids=None)`

Creates a new Predict job for a given list of sequences and a trained model.

#### Parameters

| Name        | Type               | Description                                                    | Default    |
|-------------|--------------------|----------------------------------------------------------------|------------|
| `sequences` | List               | The list of sequences to be used for the Predict job.          | _required_ |
| `train_job` | TrainFuture        | The train job object representing the trained model.           | _required_ |
| `model_ids` | typing.List\[str\] | The list of model ids to be used for Predict. Default is None. | `None`     |

#### Returns

| Type          | Description                                  |
|---------------|----------------------------------------------|
| PredictFuture | The job object representing the Predict job. |

#### Raises

| Type                  | Description                                                                                                       |
|-----------------------|-------------------------------------------------------------------------------------------------------------------|
| InvalidParameterError | If the sequences are not of the same length as the assay data or if the train job has not completed successfully. |
| InvalidParameterError | If BOTH train_job and model_ids are specified                                                                     |
| InvalidParameterError | If NEITHER train_job or model_ids is specified                                                                    |
| APIError              | If the backend refuses the job (due to sequence length or invalid inputs)                                         |

### create_predict_single_site { #openprotein.api.predict.PredictAPI.create_predict_single_site }

`api.predict.PredictAPI.create_predict_single_site(self, sequence, train_job, model_ids=None)`

Creates a new Predict job for single site mutation analysis with a trained model.

#### Parameters

| Name        | Type               | Description                                                    | Default    |
|-------------|--------------------|----------------------------------------------------------------|------------|
| `sequence`  | str                | The sequence for single site analysis.                         | _required_ |
| `train_job` | TrainFuture        | The train job object representing the trained model.           | _required_ |
| `model_ids` | typing.List\[str\] | The list of model ids to be used for Predict. Default is None. | `None`     |

#### Returns

| Type          | Description                                  |
|---------------|----------------------------------------------|
| PredictFuture | The job object representing the Predict job. |

#### Raises

| Type                  | Description                                                                                                       |
|-----------------------|-------------------------------------------------------------------------------------------------------------------|
| InvalidParameterError | If the sequences are not of the same length as the assay data or if the train job has not completed successfully. |
| InvalidParameterError | If BOTH train_job and model_ids are specified                                                                     |
| InvalidParameterError | If NEITHER train_job or model_ids is specified                                                                    |
| APIError              | If the backend refuses the job (due to sequence length or invalid inputs)                                         |

### get_prediction_results { #openprotein.api.predict.PredictAPI.get_prediction_results }

`api.predict.PredictAPI.get_prediction_results(self, job_id, page_size=None, page_offset=None)`

Retrieves the results of a Predict job.

#### Parameters

| Name          | Type                   | Description                                                                       | Default    |
|---------------|------------------------|-----------------------------------------------------------------------------------|------------|
| `job_id`      | str                    | The ID of the Predict job.                                                        | _required_ |
| `page_size`   | typing.Optional\[int\] | The number of results to be returned per page. If None, all results are returned. | `is None`  |
| `page_offset` | typing.Optional\[int\] | The number of results to skip. If None, defaults to 0.                            | `is None`  |

#### Returns

| Type       | Description                                  |
|------------|----------------------------------------------|
| PredictJob | The job object representing the Predict job. |

#### Raises

| Type      | Description                          |
|-----------|--------------------------------------|
| HTTPError | If the GET request does not succeed. |

### get_single_site_prediction_results { #openprotein.api.predict.PredictAPI.get_single_site_prediction_results }

`api.predict.PredictAPI.get_single_site_prediction_results(self, job_id, page_size=None, page_offset=None)`

Retrieves the results of a single site Predict job.

#### Parameters

| Name          | Type                   | Description                                                                       | Default    |
|---------------|------------------------|-----------------------------------------------------------------------------------|------------|
| `job_id`      | str                    | The ID of the Predict job.                                                        | _required_ |
| `page_size`   | typing.Optional\[int\] | The number of results to be returned per page. If None, all results are returned. | `is None`  |
| `page_offset` | typing.Optional\[int\] | The page number to start retrieving results from. If None, defaults to 0.         | `is None`  |

#### Returns

| Type                 | Description                                              |
|----------------------|----------------------------------------------------------|
| PredictSingleSiteJob | The job object representing the single site Predict job. |

#### Raises

| Type      | Description                          |
|-----------|--------------------------------------|
| HTTPError | If the GET request does not succeed. |

### load_job { #openprotein.api.predict.PredictAPI.load_job }

`api.predict.PredictAPI.load_job(self, job_id)`

Reload a Submitted job to resume from where you left off!

#### Parameters

| Name     | Type   | Description                                               | Default    |
|----------|--------|-----------------------------------------------------------|------------|
| `job_id` | str    | The identifier of the job whose details are to be loaded. | _required_ |

#### Returns

| Type   | Description   |
|--------|---------------|
| Job    | Job           |

#### Raises

| Type       | Description                         |
|------------|-------------------------------------|
| HTTPError  | If the request to the server fails. |
| InvalidJob | If the Job is of the wrong type     |