# api.embedding.SVDModel { #openprotein.api.embedding.SVDModel }

`api.embedding.SVDModel(self, session, metadata)`

Class providing embedding endpoint for SVD models.         Also allows retrieving embeddings of sequences used to fit the SVD with `get`.

## Methods

| Name | Description |
| --- | --- |
| [delete](#openprotein.api.embedding.SVDModel.delete) | Delete this SVD model. |
| [embed](#openprotein.api.embedding.SVDModel.embed) | Use this SVD model to reduce embeddings results.  |
| [get_embeddings](#openprotein.api.embedding.SVDModel.get_embeddings) | Get SVD embedding results for this model. |
| [get_inputs](#openprotein.api.embedding.SVDModel.get_inputs) | Get sequences used for embeddings job. |
| [get_job](#openprotein.api.embedding.SVDModel.get_job) | Get job associated with this SVD model |
| [get_model](#openprotein.api.embedding.SVDModel.get_model) | Fetch embeddings model |

### delete { #openprotein.api.embedding.SVDModel.delete }

`api.embedding.SVDModel.delete(self)`

Delete this SVD model.

### embed { #openprotein.api.embedding.SVDModel.embed }

`api.embedding.SVDModel.embed(self, sequences)`

Use this SVD model to reduce embeddings results. 

#### Parameters

| Name        | Type                 | Description                | Default    |
|-------------|----------------------|----------------------------|------------|
| `sequences` | typing.List\[bytes\] | List of protein sequences. | _required_ |

#### Returns

| Type                  | Description                         |
|-----------------------|-------------------------------------|
| EmbeddingResultFuture | Class for further job manipulation. |

### get_embeddings { #openprotein.api.embedding.SVDModel.get_embeddings }

`api.embedding.SVDModel.get_embeddings(self)`

Get SVD embedding results for this model.

#### Returns

| Type                                                     | Description   |
|----------------------------------------------------------|---------------|
| EmbeddingResultFuture: class for futher job manipulation |               |

### get_inputs { #openprotein.api.embedding.SVDModel.get_inputs }

`api.embedding.SVDModel.get_inputs(self)`

Get sequences used for embeddings job.

#### Returns

| Type                           | Description   |
|--------------------------------|---------------|
| List[bytes]: list of sequences |               |

### get_job { #openprotein.api.embedding.SVDModel.get_job }

`api.embedding.SVDModel.get_job(self)`

Get job associated with this SVD model

### get_model { #openprotein.api.embedding.SVDModel.get_model }

`api.embedding.SVDModel.get_model(self)`

Fetch embeddings model