# api.data.AssayDataset { #openprotein.api.data.AssayDataset }

`api.data.AssayDataset(self, session, metadata)`

Future Job for manipulating results

## Methods

| Name | Description |
| --- | --- |
| [get_first](#openprotein.api.data.AssayDataset.get_first) | Get head slice of assay data. |
| [get_slice](#openprotein.api.data.AssayDataset.get_slice) | Get a slice of assay data. |
| [list_models](#openprotein.api.data.AssayDataset.list_models) | List models assoicated with assay. |
| [update](#openprotein.api.data.AssayDataset.update) | Update the assay metadata. |

### get_first { #openprotein.api.data.AssayDataset.get_first }

`api.data.AssayDataset.get_first(self)`

Get head slice of assay data.

#### Returns

| Type             | Description                                   |
|------------------|-----------------------------------------------|
| pandas.DataFrame | Dataframe containing the slice of assay data. |

### get_slice { #openprotein.api.data.AssayDataset.get_slice }

`api.data.AssayDataset.get_slice(self, start, end)`

Get a slice of assay data.

#### Parameters

| Name    | Type   | Description               | Default    |
|---------|--------|---------------------------|------------|
| `start` | int    | Start index of the slice. | _required_ |
| `end`   | int    | End index of the slice.   | _required_ |

#### Returns

| Type             | Description                                   |
|------------------|-----------------------------------------------|
| pandas.DataFrame | Dataframe containing the slice of assay data. |

### list_models { #openprotein.api.data.AssayDataset.list_models }

`api.data.AssayDataset.list_models(self)`

List models assoicated with assay.

#### Returns

| Type   | Description    |
|--------|----------------|
| List   | List of models |

### update { #openprotein.api.data.AssayDataset.update }

`api.data.AssayDataset.update(self, assay_name=None, assay_description=None)`

Update the assay metadata.

#### Parameters

| Name                | Type   | Description                                    | Default   |
|---------------------|--------|------------------------------------------------|-----------|
| `assay_name`        | str    | New name of the assay, by default None.        | `None`    |
| `assay_description` | str    | New description of the assay, by default None. | `None`    |

#### Returns

| Type   | Description   |
|--------|---------------|
| None   |               |