# api.poet.PoetScoreFuture { #openprotein.api.poet.PoetScoreFuture }

`api.poet.PoetScoreFuture(self, session, job, page_size=config.POET_PAGE_SIZE)`

Represents a result of a PoET scoring job.

## Attributes

| Name      | Type       | Description                                      |
|-----------|------------|--------------------------------------------------|
| session   | APISession | An instance of APISession for API interactions.  |
| job       | Job        | The PoET scoring job.                            |
| page_size | int        | The number of results to fetch in a single page. |

## Methods

get(verbose=False)
    Get the final results of the PoET  job.

## Methods

| Name | Description |
| --- | --- |
| [get](#openprotein.api.poet.PoetScoreFuture.get) | Get the final results of the PoET scoring job. |

### get { #openprotein.api.poet.PoetScoreFuture.get }

`api.poet.PoetScoreFuture.get(self, verbose=False)`

Get the final results of the PoET scoring job.

#### Parameters

| Name      | Type   | Description                                       | Default   |
|-----------|--------|---------------------------------------------------|-----------|
| `verbose` | bool   | If True, print verbose output. Defaults to False. | `False`   |

#### Raises

| Type     | Description                                |
|----------|--------------------------------------------|
| APIError | If there is an issue with the API request. |

#### Returns

| Type                                              | Description                                                         |
|---------------------------------------------------|---------------------------------------------------------------------|
| typing.List\[openprotein.models.PoetScoreResult\] | A list of PoetScoreResult objects representing the scoring results. |