package:
  name: openprotein-python
  version: "0.5.0"

source:
  path: ../

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3.10,<3.11
    - hatchling >=1.25.0,<2
  host:
    - python >=3.10,<3.11
    - pip
    - hatchling >=1.25.0,<2
  run:
    - python >=3.10,<3.11
    - requests >=2.32.3,<3
    - pydantic >=2.5,<3
    - tqdm >=4.66.5,<5
    - pandas >=2.1.4,<3
    - numpy >=2.1.1,<3

about:
  home: https://www.openprotein.ai/
  license: MIT
  summary: OpenProtein Python interface.
  description: A Python interface for OpenProtein.
  doc_url: https://docs.openprotein.ai/
  dev_url: https://github.com/OpenProteinAI/openprotein-python
