# api.poet.PoetAPI { #openprotein.api.poet.PoetAPI }

`api.poet.PoetAPI(self, session)`

API interface for calling Poet and Align endpoints

## Methods

| Name | Description |
| --- | --- |
| [create_msa](#openprotein.api.poet.PoetAPI.create_msa) | Construct an MSA via homology search with the seed sequence. |
| [generate](#openprotein.api.poet.PoetAPI.generate) | Generate protein sequences conditioned on a prompt. |
| [get_msa](#openprotein.api.poet.PoetAPI.get_msa) | Get generated MSA for a given job. |
| [get_msa_job](#openprotein.api.poet.PoetAPI.get_msa_job) | Get MSA job based on job_id. |
| [get_prompt](#openprotein.api.poet.PoetAPI.get_prompt) | Get prompts for a given job. |
| [get_prompt_job](#openprotein.api.poet.PoetAPI.get_prompt_job) | Get prompt job based on job_id. |
| [get_seed](#openprotein.api.poet.PoetAPI.get_seed) | Get input data for a given msa job. |
| [load_msa_job](#openprotein.api.poet.PoetAPI.load_msa_job) | Reload a previously ran MSA job to resume where you left off. |
| [load_poet_job](#openprotein.api.poet.PoetAPI.load_poet_job) | Reload a previously ran Poet job to resume where you left off. |
| [load_prompt_job](#openprotein.api.poet.PoetAPI.load_prompt_job) | Reload a previously ran prompt job to resume where you left off. |
| [score](#openprotein.api.poet.PoetAPI.score) | Score query sequences using the specified prompt. |
| [single_site](#openprotein.api.poet.PoetAPI.single_site) | Score all single substitutions of the query sequence using the specified prompt. |
| [upload_msa](#openprotein.api.poet.PoetAPI.upload_msa) | Upload an MSA from file. |
| [upload_prompt](#openprotein.api.poet.PoetAPI.upload_prompt) | Directly upload a prompt. |

### create_msa { #openprotein.api.poet.PoetAPI.create_msa }

`api.poet.PoetAPI.create_msa(self, seed)`

Construct an MSA via homology search with the seed sequence.

#### Parameters

| Name   | Type   | Description                             | Default    |
|--------|--------|-----------------------------------------|------------|
| `seed` | bytes  | Seed sequence for the MSA construction. | _required_ |

#### Raises

| Type     | Description                                |
|----------|--------------------------------------------|
| APIError | If there is an issue with the API request. |

#### Returns

| Type   | Description                                                |
|--------|------------------------------------------------------------|
| MSAJob | Job object containing the details of the MSA construction. |

### generate { #openprotein.api.poet.PoetAPI.generate }

`api.poet.PoetAPI.generate(self, prompt, num_samples=100, temperature=1.0, topk=None, topp=None, max_length=1000, seed=None)`

Generate protein sequences conditioned on a prompt.

#### Parameters

| Name          | Type      | Description                                                                              | Default    |
|---------------|-----------|------------------------------------------------------------------------------------------|------------|
| `prompt`      | PromptJob | The prompt to use for generating sequences.                                              | _required_ |
| `num_samples` | int       | The number of samples to generate, by default 100.                                       | `100`      |
| `temperature` | float     | The temperature for sampling. Higher values produce more random outputs, by default 1.0. | `1.0`      |
| `topk`        | int       | The number of top-k residues to consider during sampling, by default None.               | `None`     |
| `topp`        | float     | The cumulative probability threshold for top-p sampling, by default None.                | `None`     |
| `max_length`  | int       | The maximum length of generated proteins, by default 1000.                               | `1000`     |
| `seed`        | int       | Seed for random number generation, by default a random number.                           | `None`     |

#### Raises

| Type     | Description                                |
|----------|--------------------------------------------|
| APIError | If there is an issue with the API request. |

#### Returns

| Type   | Description                                                                 |
|--------|-----------------------------------------------------------------------------|
| Job    | An object representing the status and information about the generation job. |

### get_msa { #openprotein.api.poet.PoetAPI.get_msa }

`api.poet.PoetAPI.get_msa(self, job)`

Get generated MSA for a given job.

#### Parameters

| Name   | Type   | Description                         | Default    |
|--------|--------|-------------------------------------|------------|
| `job`  | Job    | The job for which to retrieve data. | _required_ |

#### Returns

| Type       | Description                         |
|------------|-------------------------------------|
| csv.reader | A CSV reader for the response data. |

### get_msa_job { #openprotein.api.poet.PoetAPI.get_msa_job }

`api.poet.PoetAPI.get_msa_job(self, job_id)`

Get MSA job based on job_id.

#### Parameters

| Name     | Type   | Description             | Default    |
|----------|--------|-------------------------|------------|
| `job_id` | str    | job ID for a prompt job | _required_ |

#### Returns

| Type   | Description           |
|--------|-----------------------|
| MSAJob | A prompt job instance |

### get_prompt { #openprotein.api.poet.PoetAPI.get_prompt }

`api.poet.PoetAPI.get_prompt(self, job, prompt_index=None)`

Get prompts for a given job.

#### Parameters

| Name           | Type                   | Description                                                   | Default    |
|----------------|------------------------|---------------------------------------------------------------|------------|
| `job`          | Job                    | The job for which to retrieve data.                           | _required_ |
| `prompt_index` | typing.Optional\[int\] | The replicate number for the prompt (input_type=-PROMPT only) | `None`     |

#### Returns

| Type       | Description                         |
|------------|-------------------------------------|
| csv.reader | A CSV reader for the response data. |

### get_prompt_job { #openprotein.api.poet.PoetAPI.get_prompt_job }

`api.poet.PoetAPI.get_prompt_job(self, job_id)`

Get prompt job based on job_id.

#### Parameters

| Name     | Type   | Description             | Default    |
|----------|--------|-------------------------|------------|
| `job_id` | str    | job ID for a prompt job | _required_ |

#### Returns

| Type      | Description           |
|-----------|-----------------------|
| PromptJob | A prompt job instance |

### get_seed { #openprotein.api.poet.PoetAPI.get_seed }

`api.poet.PoetAPI.get_seed(self, job)`

Get input data for a given msa job.

#### Parameters

| Name   | Type   | Description                         | Default    |
|--------|--------|-------------------------------------|------------|
| `job`  | Job    | The job for which to retrieve data. | _required_ |

#### Returns

| Type       | Description                         |
|------------|-------------------------------------|
| csv.reader | A CSV reader for the response data. |

### load_msa_job { #openprotein.api.poet.PoetAPI.load_msa_job }

`api.poet.PoetAPI.load_msa_job(self, msa_id)`

Reload a previously ran MSA job to resume where you left off.

#### Parameters

| Name     | Type   | Description   | Default    |
|----------|--------|---------------|------------|
| `msa_id` | str    | ID for job.   | _required_ |

#### Raises

| Type       | Description                  |
|------------|------------------------------|
| InvalidJob | If job is of incorrect type. |

#### Returns

| Type         | Description              |
|--------------|--------------------------|
| PromptFuture | Job to resume workflows. |

### load_poet_job { #openprotein.api.poet.PoetAPI.load_poet_job }

`api.poet.PoetAPI.load_poet_job(self, job_id)`

Reload a previously ran Poet job to resume where you left off.

#### Parameters

| Name     | Type   | Description   | Default    |
|----------|--------|---------------|------------|
| `job_id` | str    | ID for job.   | _required_ |

#### Raises

| Type       | Description                  |
|------------|------------------------------|
| InvalidJob | If job is of incorrect type. |

#### Returns

| Type       | Description              |
|------------|--------------------------|
| PoetFuture | Job to resume workflows. |

### load_prompt_job { #openprotein.api.poet.PoetAPI.load_prompt_job }

`api.poet.PoetAPI.load_prompt_job(self, prompt_id)`

Reload a previously ran prompt job to resume where you left off.

#### Parameters

| Name        | Type   | Description   | Default    |
|-------------|--------|---------------|------------|
| `prompt_id` | str    | ID for job.   | _required_ |

#### Raises

| Type       | Description                  |
|------------|------------------------------|
| InvalidJob | If job is of incorrect type. |

#### Returns

| Type         | Description              |
|--------------|--------------------------|
| PromptFuture | Job to resume workflows. |

### score { #openprotein.api.poet.PoetAPI.score }

`api.poet.PoetAPI.score(self, prompt, queries)`

Score query sequences using the specified prompt.

#### Parameters

| Name      | Type                 | Description                                  | Default    |
|-----------|----------------------|----------------------------------------------|------------|
| `prompt`  | Prompt               | Prompt job to use for scoring the sequences. | _required_ |
| `queries` | typing.List\[bytes\] | Sequences to score.                          | _required_ |

#### Returns

| Type    | Description                        |
|---------|------------------------------------|
| results | The scores of the query sequences. |

### single_site { #openprotein.api.poet.PoetAPI.single_site }

`api.poet.PoetAPI.single_site(self, prompt, sequence)`

Score all single substitutions of the query sequence using the specified prompt.

#### Parameters

| Name       | Type   | Description                                  | Default    |
|------------|--------|----------------------------------------------|------------|
| `prompt`   | Prompt | Prompt job to use for scoring the sequences. | _required_ |
| `sequence` | bytes  | Sequence to analyse.                         | _required_ |

#### Returns

| Type    | Description                         |
|---------|-------------------------------------|
| results | The scores of the mutated sequence. |

### upload_msa { #openprotein.api.poet.PoetAPI.upload_msa }

`api.poet.PoetAPI.upload_msa(self, msa_file)`

Upload an MSA from file.

#### Parameters

| Name       | Type   | Description                                             | Default    |
|------------|--------|---------------------------------------------------------|------------|
| `msa_file` | str    | Ready-made MSA. If not provided, default value is None. | _required_ |

#### Raises

| Type     | Description                                |
|----------|--------------------------------------------|
| APIError | If there is an issue with the API request. |

#### Returns

| Type   | Description                                          |
|--------|------------------------------------------------------|
| MSAJob | Job object containing the details of the MSA upload. |

### upload_prompt { #openprotein.api.poet.PoetAPI.upload_prompt }

`api.poet.PoetAPI.upload_prompt(self, prompt_file)`

Directly upload a prompt.

Bypass post_msa and prompt_post steps entirely. In this case PoET will use the prompt as is.
You can specify multiple prompts (one per replicate) with an <END_PROMPT> and newline between CSVs.

#### Parameters

| Name          | Type     | Description                                     | Default    |
|---------------|----------|-------------------------------------------------|------------|
| `prompt_file` | BinaryIO | Binary I/O object representing the prompt file. | _required_ |

#### Raises

| Type     | Description                                |
|----------|--------------------------------------------|
| APIError | If there is an issue with the API request. |

#### Returns

| Type      | Description                                                      |
|-----------|------------------------------------------------------------------|
| PromptJob | An object representing the status and results of the prompt job. |