# api.data.DataAPI { #openprotein.api.data.DataAPI }

`api.data.DataAPI(self, session)`

API interface for calling AssayData endpoints

## Methods

| Name | Description |
| --- | --- |
| [create](#openprotein.api.data.DataAPI.create) | Create a new assay dataset. |
| [get](#openprotein.api.data.DataAPI.get) | Get an assay dataset by its ID. |
| [list](#openprotein.api.data.DataAPI.list) | List all assay datasets. |
| [load_job](#openprotein.api.data.DataAPI.load_job) | Reload a Submitted job to resume from where you left off! |

### create { #openprotein.api.data.DataAPI.create }

`api.data.DataAPI.create(self, table, name, description=None)`

Create a new assay dataset.

#### Parameters

| Name          | Type             | Description                                        | Default    |
|---------------|------------------|----------------------------------------------------|------------|
| `table`       | pandas.DataFrame | DataFrame containing the assay data.               | _required_ |
| `name`        | str              | Name of the assay dataset.                         | _required_ |
| `description` | str              | Description of the assay dataset, by default None. | `None`     |

#### Returns

| Type         | Description            |
|--------------|------------------------|
| AssayDataset | Created assay dataset. |

### get { #openprotein.api.data.DataAPI.get }

`api.data.DataAPI.get(self, assay_id)`

Get an assay dataset by its ID.

#### Parameters

| Name       | Type   | Description              | Default    |
|------------|--------|--------------------------|------------|
| `assay_id` | str    | ID of the assay dataset. | _required_ |

#### Returns

| Type         | Description                          |
|--------------|--------------------------------------|
| AssayDataset | Assay dataset with the specified ID. |

#### Raises

| Type     | Description                                     |
|----------|-------------------------------------------------|
| KeyError | If no assay dataset with the given ID is found. |

### list { #openprotein.api.data.DataAPI.list }

`api.data.DataAPI.list(self)`

List all assay datasets.

#### Returns

| Type                                             | Description                 |
|--------------------------------------------------|-----------------------------|
| typing.List\[openprotein.api.data.AssayDataset\] | List of all assay datasets. |

### load_job { #openprotein.api.data.DataAPI.load_job }

`api.data.DataAPI.load_job(self, assay_id)`

Reload a Submitted job to resume from where you left off!

#### Parameters

| Name       | Type   | Description                                               | Default    |
|------------|--------|-----------------------------------------------------------|------------|
| `assay_id` | str    | The identifier of the job whose details are to be loaded. | _required_ |

#### Returns

| Type   | Description   |
|--------|---------------|
| Job    | Job           |

#### Raises

| Type       | Description                         |
|------------|-------------------------------------|
| HTTPError  | If the request to the server fails. |
| InvalidJob | If the Job is of the wrong type     |