# api.embedding.ProtembedModel { #openprotein.api.embedding.ProtembedModel }

`api.embedding.ProtembedModel(self, session, model_id, metadata=None)`

Class providing inference endpoints for protein embedding models served by OpenProtein.

## Methods

| Name | Description |
| --- | --- |
| [attn](#openprotein.api.embedding.ProtembedModel.attn) | Attention embeddings for sequences using this model. |
| [embed](#openprotein.api.embedding.ProtembedModel.embed) | Embed sequences using this model. |
| [fit_svd](#openprotein.api.embedding.ProtembedModel.fit_svd) | Fit an SVD on the embedding results of this model.  |
| [get_metadata](#openprotein.api.embedding.ProtembedModel.get_metadata) | Get model metadata for this model. |
| [logits](#openprotein.api.embedding.ProtembedModel.logits) | logit embeddings for sequences using this model. |

### attn { #openprotein.api.embedding.ProtembedModel.attn }

`api.embedding.ProtembedModel.attn(self, sequences)`

Attention embeddings for sequences using this model.

#### Parameters

| Name        | Type                 | Description      | Default    |
|-------------|----------------------|------------------|------------|
| `sequences` | typing.List\[bytes\] | sequences to SVD | _required_ |

#### Returns

| Type                  | Description   |
|-----------------------|---------------|
| EmbeddingResultFuture |               |

### embed { #openprotein.api.embedding.ProtembedModel.embed }

`api.embedding.ProtembedModel.embed(self, sequences, reduction='MEAN')`

Embed sequences using this model.

#### Parameters

| Name        | Type                   | Description                             | Default    |
|-------------|------------------------|-----------------------------------------|------------|
| `sequences` | typing.List\[bytes\]   | sequences to SVD                        | _required_ |
| `reduction` | typing.Optional\[str\] | embeddings reduction to use (e.g. mean) | `'MEAN'`   |

#### Returns

| Type                  | Description   |
|-----------------------|---------------|
| EmbeddingResultFuture |               |

### fit_svd { #openprotein.api.embedding.ProtembedModel.fit_svd }

`api.embedding.ProtembedModel.fit_svd(self, sequences, n_components=1024, reduction=None)`

Fit an SVD on the embedding results of this model. 

This function will create an SVDModel based on the embeddings from this model             as well as the hyperparameters specified in the args.  

#### Parameters

| Name           | Type                   | Description                                               | Default    |
|----------------|------------------------|-----------------------------------------------------------|------------|
| `sequences`    | typing.List\[bytes\]   | sequences to SVD                                          | _required_ |
| `n_components` | int                    | number of components in SVD. Will determine output shapes | `1024`     |
| `reduction`    | typing.Optional\[str\] | embeddings reduction to use (e.g. mean)                   | `None`     |

#### Returns

| Type     | Description   |
|----------|---------------|
| SVDModel |               |

### get_metadata { #openprotein.api.embedding.ProtembedModel.get_metadata }

`api.embedding.ProtembedModel.get_metadata(self)`

Get model metadata for this model.

#### Returns

| Type          | Description   |
|---------------|---------------|
| ModelMetadata |               |

### logits { #openprotein.api.embedding.ProtembedModel.logits }

`api.embedding.ProtembedModel.logits(self, sequences)`

logit embeddings for sequences using this model.

#### Parameters

| Name        | Type                 | Description      | Default    |
|-------------|----------------------|------------------|------------|
| `sequences` | typing.List\[bytes\] | sequences to SVD | _required_ |

#### Returns

| Type                  | Description   |
|-----------------------|---------------|
| EmbeddingResultFuture |               |