name: Release Conda Workflow

on:
  push:
    tags:
      - 'test*'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      # See: https://github.com/marketplace/actions/setup-miniconda
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          python-version: 3.8
          activate-environment: pytest
          environment-file: test_environment.yml
          use-mamba: true

      - name: activate env
        run: |
          conda activate pytest

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
    
      - name: Install Dependencies
        run: |
          poetry install
          pip install coverage

      - name: Run tests
        run: |
          coverage run -m pytest ./tests/api/

      - name: Build Package
        run: |
          conda install conda-build
          conda install anaconda-client
          conda build ./anaconda_build

      - name: Upload to Anaconda Cloud
        run: |
          anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
          anaconda upload ${{ steps.build.outputs.CONDA_PACKAGE }}
