name: Sphinx Build and Sync to S3

on:
  push:
    branches:
    - develop

jobs:
  build_and_sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Sphinx
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    - name: Build HTML with Sphinx
      run: |
        cd apidocs
        make html

    - name: Get bucket name
      shell: bash
      run: |
        branch=$(echo ${GITHUB_REF#refs/heads/}); \
        if [ $branch == 'develop' ]; \
        then bucket=openprotein-docs-dev; \
        elif [ $branch == 'prod' ]; \
        then bucket=openprotein-docs-prod; \
        else exit 1; fi; \
        echo $bucket; \
        echo "bucket=$bucket" >> $GITHUB_OUTPUT
      id: bucket_name
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync apidocs to S3
      env:
        AWS_S3_BUCKET: ${{ steps.bucket_name.outputs.bucket }}
      shell: bash
      run: |
        aws s3 sync apidocs/_build/html s3://${AWS_S3_BUCKET}/apidocs/
